//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.CodeStrings", typeof(CodeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string AddStream {
            get {
                return ResourceManager.GetString("AddStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel ähnelt.
        /// </summary>
        public static string AddStream_Channel {
            get {
                return ResourceManager.GetString("AddStream_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display-Name ähnelt.
        /// </summary>
        public static string AddStream_DisplayName {
            get {
                return ResourceManager.GetString("AddStream_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game ähnelt.
        /// </summary>
        public static string AddStream_Game {
            get {
                return ResourceManager.GetString("AddStream_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is favorite ähnelt.
        /// </summary>
        public static string AddStream_IsFavorite {
            get {
                return ResourceManager.GetString("AddStream_IsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string AddStream_StreamName {
            get {
                return ResourceManager.GetString("AddStream_StreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add to favorites ähnelt.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brood War ähnelt.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel doesn&apos;t exist ähnelt.
        /// </summary>
        public static string ChannelDoesntExist {
            get {
                return ResourceManager.GetString("ChannelDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check your Livestreamer path. ähnelt.
        /// </summary>
        public static string CheckLivestreamerPath {
            get {
                return ResourceManager.GetString("CheckLivestreamerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect Paths. Please check! ähnelt.
        /// </summary>
        public static string CheckPaths {
            get {
                return ResourceManager.GetString("CheckPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check your VLC path. ähnelt.
        /// </summary>
        public static string CheckVLCPath {
            get {
                return ResourceManager.GetString("CheckVLCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently running: ähnelt.
        /// </summary>
        public static string CurrentlyRunning {
            get {
                return ResourceManager.GetString("CurrentlyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diablo 3 ähnelt.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DotA 2 ähnelt.
        /// </summary>
        public static string Dota2 {
            get {
                return ResourceManager.GetString("Dota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorites ähnelt.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorite ähnelt.
        /// </summary>
        public static string FavoriteStream {
            get {
                return ResourceManager.GetString("FavoriteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found ähnelt.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a file path. ähnelt.
        /// </summary>
        public static string FilePathMissing {
            get {
                return ResourceManager.GetString("FilePathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heroes of the Storm ähnelt.
        /// </summary>
        public static string HotS {
            get {
                return ResourceManager.GetString("HotS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hearthstone ähnelt.
        /// </summary>
        public static string HS {
            get {
                return ResourceManager.GetString("HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Refresh: ähnelt.
        /// </summary>
        public static string LastRefresh {
            get {
                return ResourceManager.GetString("LastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H:mm tt ähnelt.
        /// </summary>
        public static string LastRefreshDateFormat {
            get {
                return ResourceManager.GetString("LastRefreshDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last runtime: ähnelt.
        /// </summary>
        public static string LastRunTime {
            get {
                return ResourceManager.GetString("LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livestreamer ähnelt.
        /// </summary>
        public static string LiveStreamer {
            get {
                return ResourceManager.GetString("LiveStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livestream Starter by prayzzz ähnelt.
        /// </summary>
        public static string LivestreamStarter {
            get {
                return ResourceManager.GetString("LivestreamStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading... ähnelt.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die log ähnelt.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die League of Legends ähnelt.
        /// </summary>
        public static string LoL {
            get {
                return ResourceManager.GetString("LoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nothing ähnelt.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die open in browser ähnelt.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overview ähnelt.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die paths ähnelt.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die play ähnelt.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality: ähnelt.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die remove from favorites ähnelt.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hh\:mm\:ss ähnelt.
        /// </summary>
        public static string RuntimeFormat {
            get {
                return ResourceManager.GetString("RuntimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starcraft 2 ähnelt.
        /// </summary>
        public static string SC2 {
            get {
                return ResourceManager.GetString("SC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Log ähnelt.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream already running! ähnelt.
        /// </summary>
        public static string StreamAlreadyRunning {
            get {
                return ResourceManager.GetString("StreamAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die this stream is offline ähnelt.
        /// </summary>
        public static string StreamIsOffline {
            get {
                return ResourceManager.GetString("StreamIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TeamLiquid ähnelt.
        /// </summary>
        public static string TeamLiquid {
            get {
                return ResourceManager.GetString("TeamLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Streams (by teamliquid.net) ähnelt.
        /// </summary>
        public static string TeamLiquidStreams {
            get {
                return ResourceManager.GetString("TeamLiquidStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The field needs to be filled. ähnelt.
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viewer ähnelt.
        /// </summary>
        public static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VLC ähnelt.
        /// </summary>
        public static string VLC {
            get {
                return ResourceManager.GetString("VLC", resourceCulture);
            }
        }
    }
}
